[package]
name = "mquote-impl"
version = "0.1.0"
authors = ["Denis <denis.varlakov@vdomresearch.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
proc-macro-hack = "0.5"
proc-quote = "0.2"
