[package]
name = "mquote"
version = "0.1.0"
authors = ["Denis <denis.varlakov@vdomresearch.com>"]
edition = "2018"

[dependencies]
proc-macro-hack = "0.5"
mquote-impl = { path = "./impl" }
quote = "0.6"
proc-macro2 = "0.4"

[dev-dependencies]
proc-macro2 = "0.4"
